config/routes.rb
Rails.application.routes.draw do
  get 'quotes/index'

  resources :quote

  resources :quote do
      resources :comments
  end
  root 'quotes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :quote
  validates :commenter, presence: true,
                      length: { minimum: 5}
    validates :body, presence: true,
                      length: { minimum: 5}
end

app/models/quote.rb
class Quote < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                      length: { minimum: 2}
    validates :text, presence: true,
                      length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @quote = Quote.find(params[:quote_id])
        @comment = @quote.comments.create(comment_params)
        redirect_to quote_path(@quote)
    end
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/quote_controller.rb
class QuoteController < ApplicationController
    def show
        @quote = Quote.find(params[:id])
    end
    
    def index
            @quote = Quote.all
    end

    def new
        @quote = Quote.new
    end

    def create
        @quote = Quote.new(quote_params)
        
        if @quote.save
            redirect_to @quote
        else
            render 'new'
        end
    end

    def destroy
        @quote = Quote.find(params[:id])
        @quote.destroy
        redirect_to quote_index_path
    end
    private
        def quote_params
            params.require(:quote).permit(:title, :text)
        end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Library Info System</title>
      <%= stylesheet_link_tag "style" %>
   </head>
   <body>
   <%= yield %>
 </body>
</html>

app/views/quote/index.html.erb
<div class="row">
<div class="col-sm-12 text-center quotesheading" style="padding-bottom:10px;">
<h1> Feel free to add new quote</h1>
<%= link_to 'Add Quote', new_quote_path, { :class=>"btn btn-success" } %>
</div>
</div>
<div class="row">
<% @quote.each do |quote| %>
    <div class="col-sm-12 text-center quoteText">
    <h2><%= quote.title %></h2></br>
    <p><%= quote.text %></p>
    <p><%= link_to 'Show', quote_path(quote), { :class=>"btn btn-success" } %>
    <%= link_to 'Destroy', quote_path(quote),
            method: :delete,
            :class => 'btn btn-danger',
            data: { confirm: 'Are you sure?'} %></button> </p>
    </div>
    <hr />
    <% end %>
</div>

app/views/quote/new.html.erb
<div class="row">
<div class="col-sm-12 text-center">
<h1>Create new Quote</h1>

<%= form_with scope: :quote, url: quote_index_path, local: true do |form| %>
    <% if @quote.errors.any? %>
    <div id="error_box">
      <h2>
        <%= pluralize(@quote.errors.count, "error") %> 
      </h2>
      
        <% @quote.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </ul>
    </div>
  <% end %>
   
    <p>
        <%= form.label :author %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>

    <p>
    <%= link_to 'Cancel', quote_index_path, { :class=>"btn btn-danger" } %>  <%= form.submit 'Add', :class => 'btn btn-success' %>
    </p>
    <% end %>
</div>
</div>

app/views/quote/show.html.erb
<div class="row">
<div class="col-sm-12 text-center">
<blockquote class="blockquote">
    <h1 style="color:lightgray;" class="italic">
    <%= @quote.text %>
    </h1>
<footer class="blockquote-footer">
<%= @quote.title %>
</footer>
</blockquote>
</div>
<div class="col-sm-12 text-center">
<h2>Add comment:</h2>
<%= form_with(model: [ @quote, @quote.comments.build], local: true) do |form| %>
<p>
    <%= form.label :author %><br>
    <%= form.text_field :commenter %>
</p>
<p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>

<h2 style="color:red;"> Comments</h2>
</div>
<% @quote.comments.each do |comment| %>
    <div class="col-xs-12 text-center">
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>
    </div>
<% end %>
<div class="col-xs-12 text-center">
<%= link_to 'Back', quote_index_path, { :class=>"btn btn-danger" } %>
</div>
</div>

app/views/quotes/index.html.erb
<div class="jumbotron text-center" style="margin-bottom:0">
    <h1>Welcome to Quotes App</h1>

<h3>Lets start our journey!</h3>
<div class="link">

<%= link_to 'Quotes', controller: 'quote' %>
</div>